import Head from 'next/head'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { getAllPosts } from '../lib/api'
import styles from '../styles/Home.module.scss'

const ThemeToggle = dynamic(() => import('../components/ThemeToggle/ThemeToggle'), {
  ssr: false,
})

interface HomeProps {
  allPosts: {
    title: string,
    date: string,
    author: {
      name: string,
      image: string
    },
    slug: string,
    coverImage: string
    excerpt: string
  }[]
  buildTimestamp: number
}

export default function Home({ allPosts, buildTimestamp }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        {
          allPosts.map(post => (
            <Link key={post.slug} as={`/posts/${post.slug}`} href="/posts/[slug]">
              <a className={styles.card}>
                <p>{post.title}</p>
                <p>{post.date}</p>
                <p>{post.author.name}</p>
                <p>{post.slug}</p>
                <p>{post.coverImage}</p>
                <p>{post.excerpt}</p>
              </a>
            </Link>
          ))
        }

        <p>Last updated: {new Date(buildTimestamp).toLocaleString()}</p>

        <ThemeToggle />

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/master/examples'
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        ></a>
      </footer>
    </div>
  )
}

export const getStaticProps = () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'author',
    'coverImage',
    'excerpt',
  ])
  
  return {
    props: {
      allPosts,
      buildTimestamp: Date.now()
    }
  }
}
