import Head from 'next/head'
import Link from 'next/link'
import { getAllPosts } from '../lib/postsApi'
import PostGrid from '../components/PostGrid/PostGrid'
import PostCard from '../components/PostCard/PostCard'
import Layout from '../components/Layout/Layout'
import styles from '../styles/Home.module.scss'

export interface Props {
  allPosts: {
    title: string,
    date: string,
    author: {
      name: string,
      image: string
    },
    slug: string,
    coverImage: string
    excerpt: string
  }[]
}

export default function Home({ allPosts }: Props) {
  return (
    <Layout showHero>
      <Head>
        <title>hi, i'm ash</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h2>about</h2>
        <Link href='/about'>
          <button>About</button>
        </Link>

        <h2>posts</h2>
        <PostGrid>
          {
            allPosts.map(post => (
              <PostCard
                key={post.slug}
                coverImage={post.coverImage}
                date={post.date}
                excerpt={post.excerpt}
                slug={post.slug}
                title={post.title}
              />
            ))
          }
        </PostGrid>
        <Link href='/posts'>
          <button>View all posts</button>
        </Link>
      </main>
    </Layout>
  )
}

export const getStaticProps = () => {
  const allPosts = getAllPosts()
  
  return {
    props: {
      allPosts
    }
  }
}
