name: Test and Deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Install 🔧
        run: npm install
      - name: Lint 🔧
        run: npm run lint
      - name: Typecheck 🔧
        run: npm run typecheck
      - name: Test 🔧
        run: npm test
      - name: Build 🔧
        run: npm run build
      - name: E2E 🔧
        run: |
          npx playwright install --with-deps
          npm run test-e2e-ci
      - name: Lighthouse 💡
        run: npm run test-lighthouse
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Install 🔧
        run: npm install
      - name: Build 🔧
        run: |
          npm run build
          touch out/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
